In [1]:
import numpy as np

In [3]:
taxi = np.genfromtxt('nyc_taxis.csv', delimiter = ',', skip_header = True)

In [4]:
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [5]:
taxi[0][0]

2016.0

In [10]:
taxi[:][8:9]

array([[2.0160e+03, 1.0000e+00, 1.0000e+00, 5.0000e+00, 0.0000e+00,
        2.0000e+00, 5.0000e+00, 3.6300e+01, 2.5620e+03, 1.0950e+02,
        8.0000e-01, 1.1080e+01, 1.0000e+01, 1.3138e+02, 1.0000e+00]])

In [13]:
taxi[:,7]

array([21.  , 16.29, 12.7 , ..., 17.48, 12.76, 17.54])