In [1]:
import numpy as np

In [8]:
integers = np.array([1,2,3,4,5])

In [10]:
integers

array([1, 2, 3, 4, 5])

In [11]:
integers[0]

1

In [12]:
integers[0] = 10

In [13]:
integers

array([10,  2,  3,  4,  5])

In [14]:
integers[0] = 10.2

In [16]:
integers

array([10,  2,  3,  4,  5])

In [17]:
integers.dtype

dtype('int32')

In [19]:
2 ** 31

2147483648

In [20]:
smallerIntegers = np.array([1,2,3,4,5],dtype = 'int8')

In [24]:
smallerIntegers

array([1, 2, 3, 4, 5], dtype=int8)

In [25]:
smallerIntegers[0]

1

In [26]:
integers.nbytes

20

In [27]:
smallerIntegers.nbytes

5

# Multi dimensional arrays

In [32]:
multi = np.array([[1,2,3],[4,5,6]])

In [33]:
multi

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
multi[0][0]

1

# number of dimensions

In [36]:
multi.ndim

2

# Creating numpy arrays from python lists and other python structures

In [37]:
l = [1,2,3,4,5]

In [38]:
nums = np.array(l)

In [39]:
nums

array([1, 2, 3, 4, 5])

# below list contains all the diff data types in one single list

In [41]:
arr = [1,"Hello",12.5,False]

In [42]:
narr = np.array(arr)

In [43]:
# All the elements are converted to string type
narr

array(['1', 'Hello', '12.5', 'False'], dtype='<U32')

In [44]:
tuple = (1,2,3,4,5)

In [45]:
tuple

(1, 2, 3, 4, 5)

In [46]:
arr_tuple = np.array(tuple)

In [47]:
arr_tuple

array([1, 2, 3, 4, 5])

In [48]:
nums = [[1,2,3],[4,5,6]]

In [49]:
multi = np.array(nums)

In [50]:
multi

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
multi.ndim

2

# instrinsic array creation

In [52]:
arr = np.arange(10)

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr = np.arange(0,101,2)

In [55]:
arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [56]:
# for float numbers

In [57]:
arr = np.linspace(10,20,5)

In [58]:
arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [59]:
arr = np.linspace(10,20,10)

In [60]:
arr

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [61]:
arr = np.linspace(10,20,9)

In [62]:
arr

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

# random numbers

In [64]:
arr = np.random.rand(10)

In [65]:
arr

array([0.33010566, 0.61667074, 0.33949083, 0.54940458, 0.52344035,
       0.13916058, 0.9023568 , 0.53977625, 0.71968996, 0.40588172])

In [66]:
# creating 2D array from rand

In [67]:
arr = np.random.rand(10,2)

In [68]:
arr

array([[0.26905023, 0.2914957 ],
       [0.58552076, 0.50036461],
       [0.17187893, 0.13088973],
       [0.15819222, 0.10933283],
       [0.68692784, 0.06924154],
       [0.48081713, 0.72019207],
       [0.43968355, 0.38690784],
       [0.28247945, 0.14234091],
       [0.08471637, 0.48532853],
       [0.40432035, 0.93231942]])

In [69]:
arr = np.random.rand(10,3)

In [70]:
arr

array([[0.15561418, 0.92411978, 0.55525432],
       [0.00362324, 0.70337972, 0.66764207],
       [0.77130337, 0.37703808, 0.27120144],
       [0.97224778, 0.41010017, 0.58525065],
       [0.14251286, 0.51395975, 0.37622159],
       [0.3190198 , 0.58791844, 0.91785773],
       [0.02440738, 0.12965153, 0.74938014],
       [0.78608855, 0.30605175, 0.87358386],
       [0.46399805, 0.54478416, 0.11270839],
       [0.63674552, 0.71233706, 0.54049996]])

In [71]:
arr = np.random.rand(10,2,2)

In [72]:
arr

array([[[0.26409772, 0.40686352],
        [0.46013032, 0.49106238]],

       [[0.92295207, 0.30744045],
        [0.53450092, 0.69714939]],

       [[0.68408547, 0.39820303],
        [0.24084966, 0.9144369 ]],

       [[0.75980174, 0.00228606],
        [0.71501141, 0.67990911]],

       [[0.22607498, 0.52371752],
        [0.65431962, 0.01261726]],

       [[0.70860715, 0.91887641],
        [0.29419158, 0.63045025]],

       [[0.4253668 , 0.74495176],
        [0.37972194, 0.0677333 ]],

       [[0.40123883, 0.19444088],
        [0.3643852 , 0.41476236]],

       [[0.19389584, 0.39809092],
        [0.36394853, 0.66247984]],

       [[0.62043327, 0.92432011],
        [0.92798144, 0.10480371]]])

In [43]:
# numpy.random.randint(low, high=None, size=None, dtype=int)

In [ ]:
arr = np.random.randint(0, 4, 3)

In [44]:
arr

array([3, 3, 0])

# Creating arrays with constant values

In [5]:
zeroes = np.zeros(5)

In [6]:
zeroes

array([0., 0., 0., 0., 0.])

In [7]:
zeroes.dtype

dtype('float64')

In [8]:
zeroes = np.zeros(5,dtype = 'int8')

In [9]:
zeroes

array([0, 0, 0, 0, 0], dtype=int8)

In [10]:
zeroes.dtype

dtype('int8')

In [11]:
# for ones

In [12]:
arr = np.ones(5)

In [13]:
arr

array([1., 1., 1., 1., 1.])

In [14]:
arr = np.ones(5, dtype = 'int8')

In [15]:
arr

array([1, 1, 1, 1, 1], dtype=int8)

In [19]:
# creating multi-D arrays
arr = np.ones((5,2))

In [20]:
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# creating empty array

In [22]:
arr = np.empty(5, dtype = 'int8')

In [23]:
arr

array([ 72, 108, 108, 101, 114], dtype=int8)

In [24]:
arr.fill(2)

In [25]:
arr

array([2, 2, 2, 2, 2], dtype=int8)

In [30]:
arr = np.empty((5,2), dtype = 'int8')

In [31]:
arr

array([[ 112, -128],
       [ -96,  -98],
       [  48,    2],
       [   0,    0],
       [   0,    0]], dtype=int8)

In [32]:
arr.fill(-1)

In [33]:
arr

array([[-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1]], dtype=int8)

In [34]:
multi = np.full((5,2),10)

In [35]:
multi

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [38]:
# 5 rows and 2 columns
multi.shape

(5, 2)

In [39]:
multi.size

10

In [40]:
arr = np.random.randint(0, 4, 3)

In [41]:
arr

array([3, 3, 0])

# adding, deleting and sorting numbers

In [45]:
arr = np.array([10,32,2,0,56])

In [46]:
arr

array([10, 32,  2,  0, 56])

In [48]:
arr = np.append(arr,132)

In [49]:
arr

array([ 10,  32,   2,   0,  56, 132])

In [50]:
np.append(arr,164)

array([ 10,  32,   2,   0,  56, 132, 164])

In [51]:
arr

array([ 10,  32,   2,   0,  56, 132])

In [58]:
# insert at index = 6
arr = np.insert(arr,6,164)

In [59]:
arr

array([ 10,  32,   2,   0,  56, 132, 164])

In [60]:
# delete at index = 6
arr = np.delete(arr,6)

In [61]:
arr

array([ 10,  32,   2,   0,  56, 132])

In [62]:
# sorting

In [65]:
np.sort(arr)

array([  0,   2,  10,  32,  56, 132])

In [64]:
print(np.sort(arr)[::-1])

[132  56  32  10   2   0]


In [67]:
# copy of arr

In [68]:
arr_copy = arr.copy()

In [69]:
arr_copy

array([ 10,  32,   2,   0,  56, 132])

In [71]:
# views, it creates a another reference to same array, changing one array will reflect in other too because both are same

In [72]:
arr1 = arr.view()

In [75]:
print(arr[0],arr1[0])

10 10


In [76]:
arr1[0] = 101

In [77]:
print(arr[0],arr1[0])

101 101


# reshaping arrays 

In [83]:
arr = np.arange(0,10)

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr1 = arr.reshape((2,5))

In [86]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
# In NumPy, the flatten() function is used to return a copy of the array collapsed into one dimension.
# It returns a new one-dimensional array containing all the elements of the original array in the same order

In [88]:
arr = np.ones((5,2))

In [89]:
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [91]:
arr1 = arr.flatten()

In [92]:
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
# In NumPy, the ravel() function also flattens multi-dimensional arrays into a one-dimensional array, 
# but it returns a flattened view of the original array whenever possible, rather than a copy like flatten().

In [95]:
arr1 = arr.ravel()

In [97]:
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# joining and splitting arrays

In [104]:
arr1 = np.ones(5,dtype='int8')

In [105]:
arr2 = np.zeros(5, dtype='int8')

In [107]:
arr3 = np.concatenate((arr1,arr2))

In [108]:
arr3

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int8)